on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create pull request
        id: pull_request
        shell: bash
        run: |
          # TODO: check if PR already exists
          EXISTS=$(gh pr list --base dev --head main --json number --jq '.[] | .number')
          if [ ! -z "$EXISTS" ]; then
            echo "PR already exists"
            exit 0
          fi

          gh pr create --base dev --head main \
          --title "dev - update from main" \
          --body "merge `main` into `dev`"
        env:
          GH_TOKEN: ${{ github.token }}
