on:
  push:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Sync main to dev
        uses: remarkablemark/sync-branch@v1
        with:
          base: dev
